services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: citas
      POSTGRES_PASSWORD: citas
      POSTGRES_DB: citas_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: